"""init

Revision ID: 571c34c1c425
Revises: 
Create Date: 2026-03-10 19:51:19.318962
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571c34c1c425'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_name', sa.String(length=50), nullable=False),
    sa.Column('positional_titles', sa.String(length=50), nullable=True),
    sa.Column('dept_code', sa.String(length=20), nullable=False),
    sa.Column('dept_name', sa.String(length=100), nullable=True),
    sa.Column('hospital_name', sa.String(length=100), nullable=False),
    sa.Column('out_call_date', sa.String(length=20), nullable=False),
    sa.Column('time_interval_name', sa.String(length=20), nullable=True),
    sa.Column('available_remain_num', sa.Integer(), nullable=False),
    sa.Column('available_total_num', sa.Integer(), nullable=False),
    sa.Column('schedule_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_schedules_doctor_name'), 'doctor_schedules', ['doctor_name'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_out_call_date'), 'doctor_schedules', ['out_call_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_schedules_out_call_date'), table_name='doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedules_doctor_name'), table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    # ### end Alembic commands ###
